package edu.cs3500.spreadsheets.provider.model;

import java.util.List;

import edu.cs3500.spreadsheets.model.Coord;

/**
 * To represent a view only spreadsheet. Users that use this interface cannot
 * mutate the model, so it is used only so the view cannot mutate the model directly.
 */
public interface ISpreadsheetViewOnly extends ISpreadsheetModel {
  /**
   * Gets the formula used at a certain cell.
   *
   * @param coord coordinate of cell
   * @return formula that user inputted
   */
  String getFormulaAtCoord(Coord coord);
  
  /**
   * Evaluates the given cell and returns a value.
   *
   * @param coord coordinate of cell
   * @return A Value representation of cell input
   */
  Object evaluateCell(Coord coord);
  
  /**
   * Gets the list of error messages generated by this spreadsheet during creation of cells.
   *
   * @return list of error messages
   */
  List<String> errorMessages();
  
  /**
   * Gets the list of occupied Coords in this spreadsheet.
   *
   * @return list of Coord.
   */
  List<Coord> getOccupiedCoords();

  /**
   * Gets the number of columns to be displayed in the spreadsheet view.
   * @return
   */
  int getCol();

  /**
   * Gets the number of rows to be displayed in the spreadsheet view.
   * @return
   */
  int getRow();

  
}
